services:
  - type: web
    name: gestionrh-web
    env: python
    pythonVersion: 3.10
    branch: Jenny
    plan: starter
    buildCommand: 'pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && python manage.py collectstatic --noinput'
    startCommand: 'python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000'
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
