# Generated by Django 4.2.20 on 2026-05-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('date_prise_service', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('actif', models.IntegerField()),
                ('poste', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('typecontrat', models.CharField(db_column='typeContrat', max_length=100)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=100)),
                ('date_soumission', models.DateField()),
                ('numero_suivi', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.agent')),
            ],
            options={
                'db_table': 'demande',
            },
        ),
        migrations.CreateModel(
            name='Dossieragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('taux_completude', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.agent')),
            ],
            options={
                'db_table': 'dossieragent',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('type_notification', models.CharField(max_length=100)),
                ('date_envoi', models.DateField()),
                ('lue', models.IntegerField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PosteVacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('profil_recherche', models.IntegerField()),
                ('date_publication', models.IntegerField()),
                ('date_cloture', models.IntegerField()),
                ('statut', models.IntegerField()),
                ('direction_demande', models.IntegerField()),
                ('diplome_requis', models.IntegerField()),
            ],
            options={
                'db_table': 'poste_vacant',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Soldeconge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('jours_acquis', models.IntegerField(blank=True, null=True)),
                ('jours_pris', models.IntegerField(blank=True, null=True)),
                ('jours_restants', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'soldeconge',
            },
        ),
        migrations.CreateModel(
            name='Typedemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('duree_traitement_moyenne', models.IntegerField()),
                ('acte_generable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typedemande',
            },
        ),
        migrations.CreateModel(
            name='Typepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('obligatoire', models.IntegerField(blank=True, null=True)),
                ('duree_validite', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'typepiece',
            },
        ),
        migrations.CreateModel(
            name='Demandeabsence',
            fields=[
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monapp.demande')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombrejours', models.IntegerField()),
                ('motif', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'demandeabsence',
            },
        ),
        migrations.CreateModel(
            name='Demandeconge',
            fields=[
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='monapp.demande')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombrejours', models.IntegerField()),
            ],
            options={
                'db_table': 'demandeconge',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateField()),
                ('decision', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.demande')),
            ],
            options={
                'db_table': 'validation',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_expiration', models.DateField()),
                ('date_upload', models.DateField()),
                ('valide', models.IntegerField()),
                ('cheminfichier', models.CharField(max_length=255)),
                ('dossieragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.dossieragent')),
                ('typepiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.typepiece')),
            ],
            options={
                'db_table': 'piece',
            },
        ),
        migrations.AddField(
            model_name='demande',
            name='typedemande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.typedemande'),
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField()),
                ('score_elligibilite', models.FloatField()),
                ('statut', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.agent')),
                ('postevacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.postevacant')),
            ],
            options={
                'db_table': 'candidature',
            },
        ),
        migrations.CreateModel(
            name='Avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('date_effective', models.DateField()),
                ('type_avancement', models.CharField(max_length=100)),
                ('echelon_ancien', models.CharField(max_length=200)),
                ('echelon_nouveau', models.CharField(max_length=200)),
                ('piece_justificative', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.agent')),
            ],
            options={
                'db_table': 'avancement',
            },
        ),
        migrations.CreateModel(
            name='Acteadministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('date_generation', models.DateField()),
                ('contenu', models.TextField()),
                ('fichier_pdf', models.CharField(max_length=255)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.demande')),
            ],
            options={
                'db_table': 'acteadministratif',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.agent')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.role')),
            ],
            options={
                'db_table': 'agent_role',
                'unique_together': {('agent', 'role')},
            },
        ),
    ]
