# Generated by Django 4.2.20 on 2026-05-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrole',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monapp.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='jours_acquis',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='jours_pris',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soldeconge',
            name='jours_restants',
            field=models.IntegerField(default=30),
        ),
    ]
