# Generated by Django 4.2.11 on 2026-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_agentrole_options_soldeconge_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('dateactivation', models.DateField(blank=True, db_column='dateActivation', null=True)),
            ],
            options={
                'db_table': 'compte',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='acteadministratif',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='avancement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='candidature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='demande',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='demandeabsence',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='demandeconge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dossieragent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='postevacant',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='soldeconge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='typedemande',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='typepiece',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'managed': False},
        ),
    ]
