# Generated by Django 4.2 on 2026-06-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_compte_alter_acteadministratif_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfantAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'db_table': 'enfant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(default='Note de Service', max_length=100)),
                ('date_publication', models.DateField()),
                ('fichier_pdf', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='publie', max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_service',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='acteadministratif',
            table='acte_administratif',
        ),
        migrations.AlterModelTable(
            name='demandeabsence',
            table='demande_absence',
        ),
        migrations.AlterModelTable(
            name='demandeconge',
            table='demande_conge',
        ),
        migrations.AlterModelTable(
            name='dossieragent',
            table='dossier_agent',
        ),
        migrations.AlterModelTable(
            name='soldeconge',
            table='solde_conge',
        ),
        migrations.AlterModelTable(
            name='typedemande',
            table='type_demande',
        ),
        migrations.AlterModelTable(
            name='typepiece',
            table='type_piece',
        ),
        migrations.CreateModel(
            name='BulletinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomes', models.TextField(blank=True, null=True, verbose_name='Diplômes')),
                ('profession_avant_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession avant service')),
                ('situation_militaire', models.CharField(blank=True, default='Néant', max_length=255, null=True, verbose_name='Situation militaire')),
                ('distinctions_honorifiques', models.TextField(blank=True, default='Néant', null=True, verbose_name='Distinctions honorifiques')),
                ('interruption_duree', models.CharField(blank=True, max_length=50, null=True, verbose_name='Durée interruption')),
                ('interruption_cause', models.CharField(blank=True, default='Néant', max_length=255, null=True, verbose_name='Cause interruption')),
                ('proposable_avancement', models.CharField(blank=True, default='Oui', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_info', to='monapp.agent')),
            ],
            options={
                'verbose_name': 'Information bulletin',
                'verbose_name_plural': 'Informations bulletins',
                'db_table': 'bulletin_info',
            },
        ),
    ]
